language: node_js
node_js:
  - "0.10"
before_install:
  - npm install npm@1.4 -g
  - npm install -g gulp-cli
after_success :
  - gulp build
notifications:
  email:
    recipients:
      - anab.tn@gmail.com
    on_success: always
    on_failure: always
